### PR TITLE
Eager loading

### PR DESCRIPTION
**Pull request by stevefan1999**
This PR allows certain platform to start bundling prematurely

Fixes: https://github.com/callstack/haul/issues/457

### CODE REVIEW

**Comment by jukben** [comment]
Thanks for the PR. What do you think about `eager` name? I think that it would suit better.

Also, it would be nice if it starts all platforms if you don't specify particular ones.

cc @zamotany

**Comment by stevefan1999** [comment]
@jukben The problem is I don't know the set of valid platforms🤔But yeah I'd definitely call it `eager`.

**Comment by jukben** [comment]
Wouldn't you mind to refresh the snapshots? (yarn jest --u)

**Comment by stevefan1999** [comment]
ah, yes, the docs needs to be updated.

https://github.com/callstack/haul/blob/next/docs/CLI%20Commands.md

**Comment by jukben** [comment]
We can handle it in next PR 👍

**Pull request merged**
