### PR TITLE
Prototype Docusaurus website

### PR DESCRIPTION
**Pull request by FLGMwt**
#325 

Taking a stab at the docusaurus website, mostly to set it up. I'm garbage at UX, so most of the work was just getting the docs & markdown to play nicely w/ docusaurus. 

Of note, I flattened and namespaced the `docs/` dir since docusaurus expects it to be flat. 

I added my company to the "users" array mostly just to see it working w/ multiple users. I don't mind taking it out.

I used the browns from the haul logo box, and the brown on the site chrome looks a little bland, but I think it's passable? Wouldn't mind recommendations there ;D

Check it out on your local w/ `cd website && npm i && npm start`|`cd website && yarn && yarn start`, then opening up http://localhost:3000. 

image

image

image

image

### CODE REVIEW

**Comment by satya164** [comment]
Thank you for your work! I am not a fan of the colors, but I guess we can change it :)

**Comment by thymikee** [comment]
@FLGMwt can you fix lint (prettier mostly) errors?

**Comment by jukben** [comment]
@thymikee i've fixed the ESlint issues so this is ready to go as well.

**Comment by thymikee** [comment]
Awesome, thank you guys!

**Comment by FLGMwt** [comment]
Ah, sorry missed the last bump. Thanks, @jukben!

**Pull request merged**
