### PR TITLE
fix(deps): switch to open

### PR DESCRIPTION
**Pull request by jamesgeorge007**
### Summary

[opn](https://www.npmjs.com/package/opn) was recently deprecated and renamed to [open](https://www.npmjs.com/package/open).

### Test plan

N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @grabbou @thymikee

**Comment by thymikee** [comment]
Cc @zamotany

**Comment by zamotany** [comment]
Yeah on `next` we already have `open` instead of `opn`. I would recommend switching to `next` branch to use Haul from. It has some rough edges yet, but it's more stable and robust. The `master` will be replaced by `next` somewhere in the future, hopefully soon.

**Comment by zamotany** [comment]
Thank you @jamesgeorge007 for this PR, but I have to close this since the revamped and now new official codebase already use `open`. Sorry for not getting this merged, but the timing was unfortunate .

**Comment by jamesgeorge007** [comment]
@zamotany No worries :smile: it would be great if you could point me to something to work upon :clap:

**Comment by jamesgeorge007** [comment]
Also, do check out [Mevn-CLI](https://github.com/madlabsinc/mevn-cli)
Consider leaving a :star: as well as giving it a try once you're free. Would really love to hear your thoughts :+1:

**Pull request closed without merging**
