### PR TITLE
fix: release only what's necessary to npm

### LINKED ISSUE #255: Configuring Jest to work with Haul
I wanted to share how I was able to get jest tests running in a compatible way with Haul. I ran into some issues at first, if we think it's worth while I'd be glad to contribute to documentation.

The first issue I ran into was this: 

```shell
 FAIL  app/__tests__/App.test.js
  ● Test suite failed to run

    The name `react-native` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or blacklist files until there remains only one of these:

      * `/Users/joltdev/jolt/code/universal/node_modules/haul/src/utils/__tests__/fixtures/node_modules/react-native/package.json` (package)
      * `/Users/joltdev/jolt/code/universal/node_modules/react-native/package.json` (package)


      at ModuleMap._assertNoDuplicates (node_modules/jest-runtime/node_modules/jest-haste-map/build/module_map.js:128:11)
      at Object.<anonymous> (app/App.js:2:18)
```
Jest does not use Haul or Webpack to actually transpile your code, so it runs into haste module issues.  You can resolve this by configuring Jest to ignore Haul's test version of react native in your `package.json`. Add the "modulePathIgnorePatterns" option to your Jest config like so:

```json
"jest": {
    "modulePathIgnorePatterns": ["<rootDir>/node_modules/haul/src/utils/__tests__/fixtures/node_modules/react-native/package.json"]
}
```
Now your tests will not fail for components that try to import `react-native`

The second issue I ran into was getting tests to resolve modules in the way I had configured in Haul.  I have a root "app" directory that I added to the resolve modules so that I could conveniently import anything in that directory (such as components)

Here is my `webpack.haul.js`:
```javascript
module.exports = function getHaulWebpackConfig(options, defaults) {
  return {
    entry: './index.js',
    module: {
      ...defaults.module,
    },
    resolve: {
      ...defaults.resolve,
      modules: ['app', 'node_modules'],
    },
  };
};
```

In order for Jest to also respect this module resolution, you need to add it to the config in your `package json`.  Add the "moduleDirectories" option like so:

```json
"jest": {
    "moduleDirectories": [
      "app",
      "node_modules"
    ]
}
```
I hope this is helpful, I wonder if it would be worth documenting some tips like this to get Haul and Jest tests working better together.

### PR DESCRIPTION
**Pull request by thymikee**
**Summary**
Fixes #255.

**Test plan**
Tested with `yarn pack`, this is what should be published now:
```sh
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
├── bin
│   └── cli.js
├── hot
│   ├── index.js
│   └── patch.js
├── package.json
├── src
│   ├── cli.js
│   ├── cliEntry.js
│   ├── commands
│   │   ├── bundle.js
│   │   ├── init.js
│   │   ├── reload.js
│   │   └── start.js
│   ├── errors.js
│   ├── hot
│   │   ├── babelPlugin.js
│   │   └── client
│   │       ├── hotApi.js
│   │       ├── hotClient.js
│   │       ├── hotPatch.js
│   │       ├── importScriptsPolyfill.js
│   │       ├── index.js
│   │       └── utils.js
│   ├── loaders
│   │   └── assetLoader.js
│   ├── logger.js
│   ├── messages
│   │   ├── bundleBuilding.js
│   │   ├── bundleBuilt.js
│   │   ├── bundleFailed.js
│   │   ├── checkingProject.js
│   │   ├── commandFailed.js
│   │   ├── commandNotImplemented.js
│   │   ├── commandSuccess.js
│   │   ├── editorNotConfigured.js
│   │   ├── enterEntryFileName.js
│   │   ├── generatedConfig.js
│   │   ├── generatingConfig.js
│   │   ├── gitAddedEntries.js
│   │   ├── gitAddingEntries.js
│   │   ├── gitAlreadyAdded.js
│   │   ├── gitNotFound.js
│   │   ├── haulCommandHelp.js
│   │   ├── haulHelp.js
│   │   ├── index.js
│   │   ├── initialBundleInformation.js
│   │   ├── initialStartInformation.js
│   │   ├── invalidProject.js
│   │   ├── overwriteConfig.js
│   │   ├── selectEntryFile.js
│   │   ├── sourceMapFileNotFound.js
│   │   ├── sourceMapInvalidFormat.js
│   │   ├── verifiedProject.js
│   │   ├── webpackCompilerPlatformNotFound.js
│   │   └── webpackConfigNotFound.js
│   ├── resolvers
│   │   ├── AssetResolver.js
│   │   └── HasteResolver.js
│   ├── server
│   │   ├── assets
│   │   │   ├── debugger.html
│   │   │   ├── debuggerWorker.js
│   │   │   └── public
│   │   │       ├── haul_icon.ico
│   │   │       └── haul_logo.png
│   │   ├── index.js
│   │   ├── middleware
│   │   │   ├── devToolsMiddleware.js
│   │   │   ├── hotMiddleware.js
│   │   │   ├── liveReloadMiddleware.js
│   │   │   ├── loggerMiddleware.js
│   │   │   ├── missingBundleMiddleware.js
│   │   │   ├── openInEditorMiddleware.js
│   │   │   ├── rawBodyMiddleware.js
│   │   │   ├── statusPageMiddleware.js
│   │   │   ├── symbolicateMiddleware.js
│   │   │   └── systraceMiddleware.js
│   │   └── util
│   │       ├── WebsocketDebuggerProxy.js
│   │       └── websocketProxy.js
│   ├── types.js
│   └── utils
│       ├── exec.js
│       ├── findProvidesModule.js
│       ├── fixRequireIssues.js
│       ├── getBabelConfig.js
│       ├── getCompilerByPlatform.js
│       ├── getReactNativeVersion.js
│       ├── getWebpackConfig.js
│       ├── haul-integrate.sh
│       ├── haulPortHandler.js
│       ├── haulProgressBar.js
│       ├── isReactNativeProject.js
│       ├── makeReactNativeConfig.js
│       ├── polyfillEnvironment.js
│       └── resolveModule.js
└── vendor
    └── polyfills
        ├── Array.es6.js
        ├── Array.prototype.es6.js
        ├── Number.es6.js
        ├── Object.es6.js
        ├── Object.es7.js
        ├── String.prototype.es6.js
        ├── babelHelpers.js
        ├── console.js
        └── error-guard.js

```

### CODE REVIEW

**Comment by satya164** [comment]
Can we use `files` array instead of `.npmignore`?

**Comment by thymikee** [comment]
Nope, because glob ignore is retarded and I can't seem to ignore `__tests__` nested in subfolders :<

**Comment by satya164** [comment]
😮

**Comment by grabbou** [comment]
tough life

**Pull request merged**
