### PR TITLE
Transition to babel 7

### PR DESCRIPTION
**Pull request by Krizzu**
So far, updated dependencies. Haul starts, but need to work on actual bundling

### CODE REVIEW

**Comment by thymikee** [comment]
This makes us >=0.56 compatible :<

**Comment by Krizzu** [comment]
Fun is over

**Comment by thymikee** [comment]
We can still use Babel 7 to compile Haul itself ;) https://github.com/callstack/haul/issues/416

**Comment by Un3qual** [comment]
Any ETA or status updates on babel 7 compatability?

**Comment by thymikee** [comment]
We don't have ETAs but we're happy to accept PRs :)
We need to put babel-core into peer dependencies and ask users to install a transition package `babel-core@^7.0.0-0`. There's a chance it will just work with such setup. As a tool/library we cannot fully transition to Babel 7, and neet this compat layer

**Pull request closed without merging**
