### PR TITLE
Upgrade ws package

### PR DESCRIPTION
**Pull request by singingwolfboy**
This is a security fix: https://nodesecurity.io/advisories/550

### CODE REVIEW

**Comment by thymikee** [comment]
Can you also update the lockfile?

**Comment by thymikee** [comment]
Also, can just migrate to v5 from v2? What about breaking changes?

**Comment by singingwolfboy** [comment]
I've updated the lockfile now.

> Have you checked if we can just migrate to v5 from v2? What about breaking changes?

No, I admit that I haven't. I saw the security problem flagged by `npm audit`, and I made this pull request. It would probably be a good idea to have someone else take a look at this package -- someone more familiar with it.

**Comment by singingwolfboy** [comment]
@jukben: I'm not very familiar with how to use the `ws` package, so I'm not the best candidate to do this upgrade. I don't want to accidentally break something! I just wanted to open this PR to alert the project maintainers that this dependency should be upgraded. If you know more about how this package works, and how `haul` uses it, maybe you should take another shot at doing this upgrade?

**Comment by akrantz** [comment]
@jukben The security vulnerability is still present, and it would be good to resolve this. Could you please complete a pull request for https://github.com/callstack/haul/commits/jukben/ws-upgrade?

**Comment by jukben** [comment]
@akrantz I'm sorry but currently I'm unable to finish it but I agree that it would be really good if someone starts where I left and smash it, finally.

**Comment by tido64** [comment]
Sorry for reviving an old PR. We got alerted on some security issues as well and are basically in the same situation. Any chance we can get this going again?

I also see that `ws` has moved to 6.2.1 since.

cc @bweggersen @chaseholland

**Pull request closed without merging**
