### PR TITLE
[WIP]: Add Windows Support

### PR DESCRIPTION
**Pull request by berwyn**
WORK IN PROGRESS -- PLEASE DON'T MERGE

As I mentioned in #104, I need support for Windows on my project in order to use Haul. I've made a first pass at it, but there's a few issues. Namely, it seems that the console polyfill fails on Windows and prevents the app from bootstrapping:

image

I'm not 100% sure how the console polyfill works, so I'd love some direction on where to take it from here!

### CODE REVIEW

**Comment by berwyn** [comment]
Digging into this a bit more, it seems like there might be a race condition here between Chakra initialising its globals and the Haul-generated package calling initializeCore. Still digging to find which code is being problematic here, but I tend to think it's something with how Haul's `polyfillEnvironment` works, given that this works with the RN Packager but not Haul.

**Comment by satya164** [comment]
cc @axemclion

**Comment by grabbou** [comment]
CC: @rozele how are you integrating with packager in terms of setting up environment? Are there any pitfalls in particular that you would be interested in solving here?

**Comment by grabbou** [comment]
Thanks for your contribution. I am going to close it for now due to inactivity and no real interest from Callstack to land it. If there's anyone willing to contribute to this, please get in touch.

**Pull request closed without merging**
